### PR TITLE
Loosen up url validator

### PR DESCRIPTION
**Pull request by rmarescu**
URL validator is a little bit restrictive at this moment. Loosening it up until a better validation is implemented.

### CODE REVIEW

**Comment by gshaw** [comment]
I don't like that `h ttp://example.com` now validates.  That is silly.

Why not just escape the URL before testing?  Example: `URI.parse(URI.escape("http://example.com?a=b|c"))`

**Comment by rmarescu** [comment]
Not sure how feasible would be to encode unsafe characters if the URL already contains escaped characters.

Let's say the URL that needs to be validated  is `http://example.com?foo=a|b&redirect=http%3A%2F%2Fexample.com%2Fdestination%3Ffoo%3Dbar%26baz%3Dqux`
`redirect` value is the encoded URL `http://example.com/destination?foo=bar&baz=qux`
Using `URI.escape` will generate `http://example.com?foo=a%7Cb&redirect=http%253A%252F%252Fexample.com%252Fdestination%253Ffoo%253Dbar%2526baz%253Dqux`. While this would pass validation, the `redirect` param now contains a URL that has been encoded twice, therefore would not work as expected.

**Comment by gshaw** [comment]
My idea was to not change the original URL, just encode it for purposes of running it through `URI.parse` in the validator but then "h ttp://example.com" will also validate which isn't good :)

[RFC 3986 Section 2.2](http://tools.ietf.org/html/rfc3986#section-2.2) doesn't explicitly mention that | has to be encoded or not encoded.  I believe it's in the ASCII set so it should be fine buy obviously URI.parse disagrees.

So back to your original pull request.  Just add \A and \z to the regex being checked and it will ensure that the string is a URL and not just contain a URL.

```
url =~ /\A#{URI::regexp}\z/
```

**Comment by rmarescu** [comment]
Good suggestion, unfortunately it doesn't work with `|`, so we are back to square one

```
irb> "http://example.com/foo/bar?a=b|c" =~ /\A#{URI::regexp}\z/
nil
irb> "http://example.com/foo/bar?a=b|c" =~ URI::regexp
0
```

**Comment by gshaw** [comment]
Could the source that is generating the | URLs have some special code that explicitly escapes the pipe character? It really feels like | is not valid in a URL and they should be escaped.
- http://stackoverflow.com/q/1856785/265940
- http://www.seroundtable.com/archives/023052.html

**Comment by rmarescu** [comment]
Probably as a best practice is better to avoid using | in URL, however here are 2 fairly big retail sites that use it:
- http://www.lowes.com/Appliances/_/N-1z13elr/pc?cm_sp=MajorAppliances-_-Home|A4-_-rebate|Appliance_Tiered_Rebate_Shop_Home
- http://www.kohls.com/catalog/mens.jsp?CN=4294723349&N=3000035504+4294723349&icid=hpmf|mfs3

While [RFC 1738 Section 2.2](http://tools.ietf.org/html/rfc1738#section-2.2) (Dec 1994) says

```
Characters can be unsafe for a number of reasons.
[...]
These characters are "{", "}", "|", "\", "^", "~", "[", "]", and "`".

All unsafe characters must always be encoded within a URL.
```

[RFC 3986](http://tools.ietf.org/html/rfc3986) (Jan 2005) doesn't include | as reserved character

```
reserved    = gen-delims / sub-delims

gen-delims  = ":" / "/" / "?" / "#" / "[" / "]" / "@"

sub-delims  = "!" / "$" / "&" / "'" / "(" / ")"
            / "*" / "+" / "," / ";" / "="
```

I've stumbled upon that Google article as well, searching for `inurl:/` doesn't return anything either.

**Pull request closed without merging**
